services:
  - type: web
    name: groupsync-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn groupsync.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: groupsync-frontend
    env: node
    buildCommand: "cd groupsync-frontend && npm install && npm run build"
    startCommand: "cd groupsync-frontend && npm run server"
