# Generated by Django 4.2 on 2026-03-18

from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_align_meetings_with_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.DateTimeField(validators=[meetings.models.validate_future_date]),
        ),
    ]
