# Generated by Django 4.2 on 2026-02-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_group_and_add_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default='', help_text='Unique invite code for joining the group', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(help_text='The owner of the group', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
