# Generated by Django 4.2 on 2026-02-25 00:00

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_and_add_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="invite_code",
            field=models.CharField(
                default=groups.models.generate_invite_code,
                editable=False,
                help_text="Invite code for joining the group",
                max_length=12,
                unique=True,
            ),
        ),
    ]
